---
title: "Umap"
author: "Matthew Huang"
date: "2/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(tidyr)
library(dplyr)
library(e1071)
library(uwot)

drugs <- read_csv("primary-screen-replicate-treatment-info.csv", col_names = TRUE) %>% 
  clean_names()
cells <- read_csv("primary-screen-cell-line-info.csv", col_names = TRUE) %>% 
  clean_names()
pools <- read_csv("primary-screen-pooling-info.csv")
```

```{r}
prism <- read_csv("primary-screen-replicate-collapsed-logfold-change.csv", col_names = TRUE) %>% 
  clean_names()

prism_long <- prism %>% 
  #slice(1:10) %>% 
  pivot_longer(cols = -x1, names_to = "drug", values_to = "log2fc")

prism_long$drug <- 
  prism_long$drug %>% 
  str_replace_all("_", "-") %>% 
  str_sub(1, 22) %>% 
  toupper()

prism_long <- prism_long %>% 
  rename(broad_id = drug,
         cell_line = x1)

prism_meta <- read_csv("primary-screen-replicate-treatment-info.csv", col_names = TRUE) %>% 
  clean_names()

prism_long <- left_join(prism_long, prism_meta, by = "broad_id")
```

```{r}
prism_umap_data <- prism_long %>% select(log2fc, purity, moa)
prism_umap_data$moa <- as.factor(prism_umap_data$moa)
prism_umap_data <- na.omit(prism_umap_data)
#Test: prism_umap_data <- prism_umap_data %>% slice(1:100)
#moa_umap <- umap(prism_umap_data, pca = 100)
moa_umap <- umap(prism_umap_data, n_neighbors = 15, min_dist = 0.001, verbose = TRUE, pca = 100)
```

```{r}
## Test: iris_umap <- umap(iris, n_neighbors = 15, min_dist = 0.001, verbose = TRUE)
```
