---
title: "ddh.com"
output:
  pdf_document:
    toc: TRUE
---
Integrate gene + drug data

##Load libraries
```{r load_block, echo=TRUE, message=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
library(here)
library(janitor)
library(feather)
library(corrr)
library(purrr)
library(beepr) #long analysis; get some coffee, and comeback when ready

#clear environment
#rm(list=ls()) 

#how long?
start_time <- Sys.time()
```

##import
```{r import}
#read current release information to set parameters for download
source(here::here("code", "current_release.R"))

##BROAD
achilles <- read_csv(achilles_url, col_names = TRUE) %>%
  `colnames<-`(str_remove_all(names(.), "\\s\\(\\d+\\)"))
save(achilles, file = here::here("data", paste0(release, "_achilles.RData")))

achilles_long <- achilles %>% 
  pivot_longer(-X1, names_to = "gene", values_to = "dep_score")

#EXPRESSION(BROAD)
expression <- read_csv(ccle_url, col_names = TRUE) %>% 
  `colnames<-`(str_remove_all(names(.), "\\s\\(\\d+\\)"))
save(expression, file = here::here("data", paste0(release, "_expression.RData")))

expression_id <- read_csv(cclemeta_url, col_names = TRUE) %>% 
  clean_names
save(expression_id, file = here::here("data", paste0(release, "_expression_id.RData")))

expression_join <- expression_id %>% 
  rename(X1 = dep_map_id) %>% 
  select(X1, stripped_cell_line_name, lineage)
save(expression_join, file = here::here("data", paste0(release, "_expression_join.RData")))

expression_long <- expression %>% 
  filter(expression$X1 %in% achilles$X1 == TRUE) %>% #matches cells
  gather("gene", "gene_expression", -X1) %>% 
  arrange(desc(gene_expression))

no_expression <- expression_long %>% 
  filter(gene_expression == 0) %>% 
  unite(X1, gene, col = "match", sep = "-", remove = TRUE) %>% 
  pull(match) %>% 
  as_tibble()

achilles_no0 <- achilles_long %>% 
  unite(X1, gene, col = "match", sep = "-", remove = FALSE) %>% 
  filter(match %in% no_expression == FALSE) %>% 
  select(-match) %>%
  spread(gene, dep_score) %>% 
  as_tibble()

na_cutoff <- na_cutoff

toomanyNAs <- achilles_no0 %>% 
  summarise_all(list(~sum(is.na(.)))) %>% 
  gather(gene, NAs) %>% 
  arrange(desc(NAs)) %>% 
  filter(NAs > na_cutoff) %>% 
  pull(gene)

achilles_clean <- achilles_no0 %>% 
  select(-one_of(toomanyNAs))

```

#add drug data
These are log-fold change collapsed replicates with outliers and controls removed
```{r}
prism <- read_csv(prism_url, col_names = TRUE)
prism_long <- prism %>% 
  #slice(1:10) %>% 
  pivot_longer(cols = -X1, names_to = "drug", values_to = "log2fc")
prism_meta <- read_csv(prismmeta_url, col_names = TRUE)

ggplot(prism_meta) +
  geom_histogram(aes(x = dose))

ggplot(prism_long) +
  geom_histogram(aes(x = log2fc))



```


#ACHILLES CORRELATION MATRIX
```{r}
achilles_cor <- achilles_clean %>% #originally 'achilles'
  select(-X1) %>% 
  correlate() #(diagonal = 0) set to 0 so easy to summarize, but should be NA; so added na.rm = TRUE to fun() in EDA
#save(achilles_cor, file = here::here("data", paste0(release, "_achilles_cor.RData")))

```

#how long?
```{r}
end_time <- Sys.time()
time_taken <- round(as.duration(start_time %--% end_time)/dminutes(1), digits = 1)
print(time_taken)
```
Approximate time to run was `r time_taken` minutes.

#print Session information for provenance and reproducibility
```{r}
utils:::print.sessionInfo(sessionInfo()[-8]) 
#You can remove an item from sessionInfo(), which is a list with a class attribute, by printing the resulting object omitting one of the list items (omitted list of packages installed, but not loaded)

```
#stamp
```{r}
lubridate::stamp("Data updated December 31, 1979")(now())
```

#beep
```{r}
beep(sound = 8) #because mario is awesome
```



