---
apiVersion: batch/v1
kind: Job
metadata:
  name: download-ddh-data
spec:
  template:
    spec:
      initContainers:
      containers:
      - name: download-ddh-data
        image: dukegcb/lando-util:0.5.4
        workingDir: /data
        env:
        - name: DDSCLIENT_CONF
          value: "/etc/ddsclient/ddsclient-config"
        - name: DDH_QUARTER
          value: 20Q1
        command:
        - "python"
        - "/etc/download-ddh-data.py"
        volumeMounts:
        - name: ddh-data
          mountPath: "/data"
        - name: ddsclient-config
          mountPath: "/etc/ddsclient"
          readOnly: true
        - name: download-ddh-data
          mountPath: "/etc/download-ddh-data.py"
          readOnly: true
          subPath: "download-ddh-data.py"
      restartPolicy: OnFailure
      volumes:
      - name: ddh-data
        persistentVolumeClaim:
          claimName: ddh-data-pvc
      - name: ddsclient-config
        secret:
          secretName: ddsclient-config-secret
      - name: download-ddh-data
        configMap:
          name: download-ddh-data

